// Generated by Xata Codegen 0.22.3. Please do not edit.
import { buildClient, buildWorkerRunner } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "notes",
    columns: [
      { name: "title", type: "string", notNull: true, defaultValue: "" },
      { name: "description", type: "string", notNull: true, defaultValue: "" },
      { name: "slug", type: "string", notNull: true, defaultValue: "" },
      { name: "markdown", type: "text", notNull: true, defaultValue: "" },
      { name: "body", type: "text", notNull: true, defaultValue: "" },
      { name: "author", type: "link", link: { table: "authors" } },
      { name: "created_at", type: "string", notNull: true, defaultValue: "" },
    ],
  },
  {
    name: "authors",
    columns: [
      { name: "name", type: "string", unique: true },
      { name: "email", type: "email", unique: true },
      { name: "avatar_url", type: "string", notNull: true, defaultValue: "" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Notes = InferredTypes["notes"];
export type NotesRecord = Notes & XataRecord;

export type Authors = InferredTypes["authors"];
export type AuthorsRecord = Authors & XataRecord;

export type DatabaseSchema = {
  notes: NotesRecord;
  authors: AuthorsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://aman-coder-workspace-aecq9c.eu-west-1.xata.sh/db/notes",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};

export const xataWorker = buildWorkerRunner<XataClient>({
  workspace: "aman-coder-workspace-aecq9c",
  worker: "cg6oeo3tbhkmciakk33g",
});
